### ISSUE TITLE
Adjust Exposure

### ISSUE THREAD

**Issue by skuong** [Insopitus/equirect2cubemap#1]
Thank you so much for this tool.
I have a feature request: I want to adjust the exposure of the image.
Please add this feature or share some resources so I can learn to do this.
Thank you.

**Comment by insopitus** [comment]
If you want to adjust the brightness of an image, the `image` crate has a method called [`brighten`](https://docs.rs/image/0.24.8/image/enum.DynamicImage.html#method.brighten) on the `DynamicImage` struct.

I'm not sure if it's a good idea to add this feature to the tool. It's more like an image editor thing to me. May I know your use case for this?

**Comment by skuong** [comment]
I want to convert to cubemap images so that I can load all images at the same time (for a web app).
The image that I got is so dark.
![image](https://github.com/Insopitus/equirect2cubemap/assets/77433349/720efce0-de95-46fd-baf2-54f672b83170)

**Comment by insopitus** [comment]
Is the source image a `.hdr` one?

**Comment by skuong** [comment]
Yes.
So I need a tone mapped image, right?

**Comment by insopitus** [comment]
Yeah, I guess you have to do the tone mapping yourself for now.

The `image` crate has an [issue about hdr decoding](https://github.com/image-rs/image/issues/1936). I'm not sure if it's related to this.

**Comment by skuong** [comment]
Got it
Thank you so much
